name: EstasiaMall
version: 0.1
author: EstasiaDevelopment<optymized>
main: de.mcestasia.estasiamall.EstasiaMallBukkitPlugin

commands:
  shopsetup:
    aliases: [mallsetup]
    description: Erstelle einen Shop